# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-15 01:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='车辆信息')),
                ('date', models.DateField(verbose_name='上牌日期')),
                ('fadongnum', models.CharField(max_length=20, verbose_name='发动机号')),
                ('mile', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='公里数')),
                ('isweixiu', models.BooleanField(default=False, verbose_name='是否维修')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='期望售价')),
                ('address', models.CharField(max_length=50, verbose_name='买车地址')),
                ('isZhaiwu', models.BooleanField(default=False, verbose_name='是否有债务')),
                ('img', models.ImageField(default='', upload_to='static/upload/car', verbose_name='车辆图片')),
                ('promise', models.TextField(null=True, verbose_name='卖家承诺')),
                ('shenhe', models.IntegerField(choices=[(0, '审核未通过'), (1, '审核中'), (2, '审核通过')], default=0, verbose_name='审核状态')),
                ('isBuy', models.BooleanField(default=False, verbose_name='是否购买')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Typeinfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '车辆信息表',
                'verbose_name': '车辆信息表',
                'db_table': 'Car',
            },
        ),
    ]
